# Use the official Dart image from Docker Hub
FROM google/dart

# Set the working directory inside the container
WORKDIR /app

# Copy all the files from your host machine's current directory into the container
COPY . /app

# Run your Dart code
CMD ["/bin/bash"]
